// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalkAPICore8.Data;

#nullable disable

namespace NZWalkAPICore8.Migrations
{
    [DbContext(typeof(NZWalkDBContext))]
    [Migration("20250704104545_seed the data for region and Differculty")]
    partial class seedthedataforregionandDifferculty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalkAPICore8.Model.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulty");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74ba7c86-388e-443e-9524-ffa05c9c6e5c"),
                            Code = "Easy"
                        },
                        new
                        {
                            Id = new Guid("d5cf834c-bd84-4d87-bef9-061a860a8c0d"),
                            Code = "Medium"
                        },
                        new
                        {
                            Id = new Guid("e7270e7a-e944-4897-9e6a-de937d8a6087"),
                            Code = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalkAPICore8.Model.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7248fc3-2585-4efb-8d1d-1c555f4087f6"),
                            Area = 8790.0,
                            Code = "AKL",
                            Lat = 342.0,
                            Long = 3434.0,
                            Name = "Auckland",
                            Population = 4545L
                        },
                        new
                        {
                            Id = new Guid("6884f7d7-ad1f-4101-8df3-7a6fa7387d81"),
                            Area = 6512.0,
                            Code = "NTL",
                            Lat = 2323.0,
                            Long = 3434.0,
                            Name = "Northland",
                            Population = 4545L
                        },
                        new
                        {
                            Id = new Guid("14ceba71-4b51-4777-9b17-46602cf66153"),
                            Area = 6543.0,
                            Code = "BOP",
                            Lat = 2323.0,
                            Long = 3434.0,
                            Name = "Bay Of Plenty",
                            Population = 4545L
                        },
                        new
                        {
                            Id = new Guid("cfa06ed2-bf65-4b65-93ed-c9d286ddb0de"),
                            Area = 2314.0,
                            Code = "WGN",
                            Lat = 2323.0,
                            Long = 3434.0,
                            Name = "Wellington",
                            Population = 4545L
                        },
                        new
                        {
                            Id = new Guid("906cb139-415a-4bbb-a174-1a1faf9fb1f6"),
                            Area = 6589.0,
                            Code = "NSN",
                            Lat = 2323.0,
                            Long = 3434.0,
                            Name = "Nelson",
                            Population = 4511L
                        },
                        new
                        {
                            Id = new Guid("f077a22e-4248-4bf6-b564-c7cf4e250263"),
                            Area = 7845.0,
                            Code = "STL",
                            Lat = 2323.0,
                            Long = 3434.0,
                            Name = "Southland",
                            Population = 78000L
                        },
                        new
                        {
                            Id = new Guid("761a465b-e718-4b45-81d1-ed17ea9b3183"),
                            Area = 1212.0,
                            Code = "WEST-DEL",
                            Lat = 2323.0,
                            Long = 3434.0,
                            Name = "WEST DELHI",
                            Population = 360000L
                        },
                        new
                        {
                            Id = new Guid("6ae537d8-5725-427c-9c8c-3406feb70332"),
                            Area = 1212.0,
                            Code = "SOUTH-DEL",
                            Lat = 2323.0,
                            Long = 3434.0,
                            Name = "SOUTH DELHI",
                            Population = 45000L
                        },
                        new
                        {
                            Id = new Guid("1ea9b01d-ae6d-4cbc-addc-20549f495a0a"),
                            Area = 235.0,
                            Code = "EAST-DEL",
                            Lat = 2393.0,
                            Long = 3634.0,
                            Name = "EAST DELHI",
                            Population = 560000L
                        });
                });

            modelBuilder.Entity("NZWalkAPICore8.Model.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalkAPICore8.Model.Domain.Walk", b =>
                {
                    b.HasOne("NZWalkAPICore8.Model.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalkAPICore8.Model.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
